name: Check
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        repo-token: secrets.GITHUB_TOKEN
